name: Automated Test
on: [push]

jobs:
  automated_test:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
        
      # Test case 2: Run with 1 number
      - name: Produce Test 2 Output
        run: python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
        
      - name: Test 2 
        run: diff test_data/test2_expected.txt test_data/test2_output.txt
        
      # Test case 3: Run with a blank file
      - name: Produce Test 3 Output
        run: python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
        
      - name: Test 3
        run: diff test_data/test3_expected.txt test_data/test3_output.txt
