name: Automated Test
on: [push]

jobs:
  automated_test:
    name: Automated Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Produce Test 1 Output From provide Input (10 numbers)
        run: python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
        
      - name: For Test 1 verify original output with expected output
        run: diff test_data/test1_expected.txt test_data/test1_output.txt

      - name: Produce Test 2 Output From provide Input (1 number) 
        run: python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
        
      - name: For Test 2 verify original output with expected output 
        run: diff test_data/test2_expected.txt test_data/test2_output.txt
        
      - name: Produce Test 3 Output From provide Input (an Empty file) 
        run: python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
        
      - name: For Test 3 verify original output with expected output 
        run: diff test_data/test3_expected.txt test_data/test3_output.txt
